### ISSUE TITLE
Make Glaceon Come from USUM

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#42]
Glaceon (F) @ Assault Vest
IVs: 0 Atk
EVs: 252 HP / 252 SpA / 4 SpD
Ability: Ice Body
Level: 100
Shiny: Yes
Modest Nature
- Blizzard
- Water Pulse
- Shadow Ball
- Hyper Voice

For some reason this set is made to come from ORAS even though its completely possible because of move tutors in USUM

**Comment by architdate** [comment]
PKHeX does not seem to think so
![image](https://user-images.githubusercontent.com/17220860/34692436-25206080-f4fb-11e7-810e-5590f327bbc0.png)

**Comment by architdate** [comment]
Should be a base PKHeX issue

**Comment by architdate** [comment]
EDIT for reference: Mismatch happens when there is no relearn moves set. PKHeX does not suggest any relearn moves as it assumes the Encounter to be the Eevee egg as received in the Nursery and not a standard hatchable egg for a Glaceon. Hence due to the reliance on PKHeX's API for finding encounters and relearn moves, this cannot be fixed gracefully. Must be hardcoded for all Eevee evolutions if `pk.Gen7 = true`
