### ISSUE TITLE
MGDB

### ISSUE THREAD

**Issue by ShadowsGod97** [architdate/PKHeX-Auto-Legality-Mod#56]
Don't know if it's possible, but it won't be more easier that the MGDB folder that it's donwloaded with the function it's just the "released" folder... it makes the file too much bigger within all "unreleased", "extras" and all that stuff

**Comment by amish995** [comment]
That was not possible because I download the repo via GitHub, to ensure that it is always the latest mgdb, and that the link won't need to be hardcoded each time there is a new release. I am assuming your problem is with the download time, and not the fact that the mgdb folder is 10mb instead of something smaller, yeah?

**Comment by architdate** [comment]
The best that can be done is removing those folders once the download is done
