### ISSUE TITLE
Serviper Sucker Punch Transfer Move

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#74]
Cerastes (Seviper) (M) @ Life Orb
Ability: Infiltrator
Shiny: Yes
EVs: 40 Atk / 252 SpA / 216 Spe
Rash Nature
- Giga Drain
- Sucker Punch
- Sludge Wave
- Flamethrower

i Tried the Automod it different Location (Crystal)
i have to it Manually
Lucky i Fix it and 
Serpiver Sucker Punch transfer Move from DPPT

![serviper transfer move sucker punch](https://user-images.githubusercontent.com/18640392/39171629-89ccac3e-47b0-11e8-833b-987e31777b1c.png)

this the file i made Manually 
[336 ★ - Cerastes - 01002884AD72.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1941299/336.-.Cerastes.-.01002884AD72.zip)

**Comment by Orionsilver** [comment]
Cerastes (Seviper) (M) @ Life Orb
Ability: Infiltrator
Shiny: Yes
EVs: 40 Atk / 252 SpA / 216 Spe
Rash Nature
- Giga Drain
- Sucker Punch
- Sludge Wave
- Flamethrower

**Comment by architdate** [comment]
Invalid Issue: Upon checking legality of this set in [Showdown](https://play.pokemonshowdown.com/teambuilder) with the format set for `[Gen 7] Anything Goes`, the following legality issues can be viewed

![image](https://user-images.githubusercontent.com/17220860/39175184-3c7dc0fe-47dc-11e8-9ed7-27599a2486fb.png)

In order to fix this according to the error, Seviper cannot have its Hidden Ability. After changing the ability to `Shed Skin` the set works in the mod.

```
Cerastes (Seviper) (M) @ Life Orb  
Ability: Shed Skin  
Shiny: Yes  
EVs: 40 Atk / 252 SpA / 216 Spe  
Rash Nature  
- Giga Drain  
- Sucker Punch  
- Sludge Wave  
- Flamethrower
```
